# Generated by Django 4.2.4 on 2024-02-23 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post_follow_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="follow",
            field=models.ManyToManyField(
                blank=True, related_name="follow", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ManyToManyField(
                blank=True, related_name="follower", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.ManyToManyField(
                blank=True, related_name="like", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(),
        ),
    ]
